{
 "title": "Dapr-Perf-Runner",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "perf_test", "label": "perf-test", "query": { "query": "label_values(perf_test)" } }
  ]
 },
 "panels": [
  {
   "title": "HTTP Response Time p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_req_duration_p50{perf_test=\"$perf_test\"}",
     "legendFormat": "{{job}}_p50 payload_size_kb={{payload_size_kb}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_req_duration_p90{perf_test=\"$perf_test\"}",
     "legendFormat": "{{job}}_p90 payload_size_kb={{payload_size_kb}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_req_duration_p95{perf_test=\"$perf_test\"}",
     "legendFormat": "{{job}}_p95 payload_size_kb={{payload_size_kb}}"
    }
   ]
  }
 ]
}